// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Use DATABASE_URL if set, otherwise use a placeholder for schema generation
// The placeholder allows prisma generate to work without a real database
const databaseUrl = (() => {
  try {
    return env("DATABASE_URL");
  } catch {
    return "postgresql://placeholder:placeholder@localhost:5432/hypergate";
  }
})();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
